### ISSUE TITLE
Cantarell font compatibility

### ISSUE THREAD

**Issue by frankstrater** [megumumpkin/megumumpkin.github.io#1]
The included Cantarell font is not compatible with mobile Safari, which doesn't render 'p' and 't' properly. If you want to use this font as a web font, the easiest way would be to use the Google font version:

https://fonts.google.com/specimen/Cantarell/tester

Otherwise, try to mimic the font definition on the official font website at https://cantarell.gnome.org/

Specifically, have a look at https://cantarell.gnome.org/assets/style.css and get the woff and otf font files

**Comment by megumumpkin** [comment]
Does the gnome.org version works for you?

**Comment by frankstrater** [comment]
> Does the gnome.org version works for you in safari?

yes

**Comment by megumumpkin** [comment]
Ok, I've updated the website just now, how does it look on Safari now?

**Comment by frankstrater** [comment]
It works! Well done.
